### ISSUE TITLE
Custom wrapper examples?

### ISSUE THREAD

**Issue by Nikola-Milovic** [aerialist7/kotlin-react-table-sample#8]
Hello @aerialist7 , sorry for raising an issue for this, don't know any other way to contact you. I was wondering if you would ever do an example similar to this one on the topic of writing custom wrappers for JS libraries? There are close to no examples and your projects have been really easy to follow and learn from. Maybe some simpler components or utility libraries from npm. Thoughts?

**Comment by aerialist7** [comment]
Hi @Nikola-Milovic,

I think that you can check the new Kotlin Wrapper - [`kotlin-react-virtual`](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-react-virtual).
It was written by me and @turansky on a basis of [React Virtual types](https://github.com/tannerlinsley/react-virtual/blob/master/types/index.d.ts).

And it is really simple utility npm-library like you want :)
